In [1]:
import lightgbm as gbm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
# import the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [3]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(300, 2)
(100, 2)
(300,)
(100,)


In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

/Users/surabhim/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/surabhim/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/surabhim/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
import lightgbm as lgb
d_train = lgb.Dataset(x_train, label=y_train)
params = {}
params['learning_rate'] = 0.05
params['boosting_type'] = 'gbdt'
params['objective'] = 'binary'
params['metric'] = 'binary_logloss'
params['sub_feature'] = 0.5
params['num_leaves'] = 10
params['min_data'] = 50
params['max_depth'] = 10
clf = lgb.train(params, d_train, 100)

In [9]:
#Prediction
y_pred=clf.predict(x_test)
new_y_pred = []
print(y_pred)
#convert into binary values
for i in range(0,100):
    if y_pred[i]>=.5:       # setting threshold to .5
        y_pred[i]=int(1)
        new_y_pred.append(1)
#         print("here")
    else:  
        #print("heree")
        y_pred[i]=int(0)
        new_y_pred.append(0)


[0.25948656 0.05101232 0.02883165 0.026061   0.00502559 0.01375631
 0.01855409 0.87367706 0.00392024 0.74647114 0.00480869 0.00467561
 0.03922073 0.1457292  0.04974321 0.77719572 0.1457292  0.04974321
 0.89337301 0.02025663 0.00502559 0.89337301 0.05101232 0.89337301
 0.01375631 0.89337301 0.1720901  0.026061   0.03922073 0.08793456
 0.1720901  0.1457292  0.61840826 0.03922073 0.00454032 0.0046885
 0.01722858 0.00526662 0.01855409 0.92018298 0.1720901  0.03084875
 0.01914876 0.02025663 0.83379864 0.00454032 0.1457292  0.85947405
 0.01375631 0.78705981 0.89337301 0.02030985 0.0048668  0.77719572
 0.8506436  0.74822209 0.03139141 0.01586316 0.92018298 0.01375631
 0.02030985 0.79564586 0.01586316 0.87367706 0.01375631 0.78705981
 0.1720901  0.00454032 0.05101232 0.13992063 0.77719572 0.02883165
 0.00392024 0.74822209 0.1720901  0.01722858 0.14592178 0.03922073
 0.92018298 0.89337301 0.89337301 0.78705981 0.00467561 0.01375631
 0.89619345 0.14592178 0.1457292  0.89337301 0.5009041  0.03000

In [10]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
print(new_y_pred)
cm = confusion_matrix(y_test, new_y_pred)
#Accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)

[0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1]


In [11]:
cm

array([[64,  4],
       [ 3, 29]])

In [12]:
accuracy

0.93

In [42]:
import lightgbm as gbm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [39]:
# import the dataset
dataset = pd.read_csv('data1/training_set/log_mini.csv')

# preprocess
# drop unnecessary columns
dataset = dataset.drop('date', axis='columns')
# drop session_id and track_id_clean
dataset = dataset.drop('session_id', axis='columns')
dataset = dataset.drop('track_id_clean', axis='columns')

print(dataset.loc[9, 'skip_2'])

# change true / false to 0 / 1 for skip_1, skip_2, skip_2, not_skipped, hist_user_behavior_is_shuffle,  premium
# map strings to integers for other features
reasons = {'trackdone': 1, 'fwdbtn': 2, 'trackerror': 8, 'remote': 7, 'clickrow': 4, 'backbtn': 3, 'playbtn': 6, 'appload': 5, 'endplay': 9, 'logout':10}
bool_vals = {False: 0, True: 1}
enc = {
    'hist_user_behavior_reason_start': reasons,
    'context_type': {'radio': 3, 'personalized_playlist': 4, 'charts': 6, 'user_collection': 2, 'editorial_playlist': 1, 'catalog': 5},
    'hist_user_behavior_reason_end': reasons,
    'skip_1' : bool_vals,
    'skip_2' : bool_vals, 
    'skip_3' : bool_vals,
    'not_skipped' : bool_vals,
    'hist_user_behavior_is_shuffle' : bool_vals,
    'premium' : bool_vals
}

for c in enc:
    if c in dataset.columns:
        dataset[c] = dataset[c].map(enc[c]).fillna(0).astype(np.uint8)
        
print(dataset.loc[9, 'skip_2'])

True
1


In [40]:
## gbm for our data
## data is not combined with track features yet

#X = dataset.drop('skip_2', axis='columns')
X = dataset.loc[:'skip_2', 'skip_3':].values
y = dataset.loc[:, 'skip_2'].values

In [43]:
dataset

session_position  session_length  skip_1  skip_2  skip_3  not_skipped  \
0                      1              20       0       0       0            1   
1                      2              20       0       0       0            1   
2                      3              20       0       0       0            1   
3                      4              20       0       0       0            1   
4                      5              20       0       0       0            1   
...                  ...             ...     ...     ...     ...          ...   
167875                16              20       0       0       0            1   
167876                17              20       0       0       0            1   
167877                18              20       0       0       0            1   
167878                19              20       0       0       0            1   
167879                20              20       0       0       0            1   

        context_switch  no_pause_before_play  short_pause_before_play  \
0                    0                     0                        0   
1                    0                     1                        0   
2                    0                     1                        0   
3                    0                     1                        0   
4                    0                     1                        0   
...                ...                   ...                      ...   
167875               0                     1                        0   
167876               0                     1                        0   
167877               0                     1                        0   
167878               0                     1                        0   
167879               0                     1                        0   

        long_pause_before_play  hist_user_behavior_n_seekfwd  \
0                            0                             0   
1                            0                             0   
2                            0                             0   
3                            0                             0   
4                            0                             0   
...                        ...                           ...   
167875                       0                             0   
167876                       0                             0   
167877                       0                             0   
167878                       0                             0   
167879                       0                             0   

        hist_user_behavior_n_seekback  hist_user_behavior_is_shuffle  \
0                                   0                              1   
1                                   0                              1   
2                                   0                              1   
3                                   0                              1   
4                                   0                              1   
...                               ...                            ...   
167875                              0                              0   
167876                              0                              0   
167877                              0                              0   
167878                              0                              0   
167879                              0                              0   

        hour_of_day  premium  context_type  hist_user_behavior_reason_start  \
0                16        1             1                                1   
1                16        1             1                                1   
2                16        1             1                                1   
3                16        1             1                                1   
4                16        1             1                                1   
...             ...      ...           ...        

In [44]:
X

array([[0, 1, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 2, 1, 1],
       [0, 1, 0, ..., 2, 1, 1],
       [0, 1, 0, ..., 2, 1, 1]])

In [45]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [46]:
print(dataset.shape)
print(X.shape)
print(y.shape)

(167880, 18)
(167880, 14)
(167880,)


In [47]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [48]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(125910, 14)
(41970, 14)
(125910,)
(41970,)


In [49]:
# # Feature Scaling
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)

In [50]:
import lightgbm as lgb
d_train = lgb.Dataset(x_train, label=y_train)
params = {}
params['learning_rate'] = 0.5
params['boosting_type'] = 'gbdt'
params['objective'] = 'binary'
params['metric'] = 'binary_logloss'
params['sub_feature'] = 0.5
params['num_leaves'] = 10
params['min_data'] = 50
params['max_depth'] = 10
clf = lgb.train(params, d_train, 100)

In [51]:
#Prediction
y_pred=clf.predict(x_test)
new_y_pred = []
print(y_pred)
#convert into binary values
for i in range(0,41970):
    if y_pred[i]>=.5:       # setting threshold to .5
        y_pred[i]=int(1)
        new_y_pred.append(1)
#         print("here")
    else:  
        #print("heree")
        y_pred[i]=int(0)
        new_y_pred.append(0)

[4.32058708e-01 9.39035379e-01 4.99138649e-01 ... 6.86066382e-08
 5.58550652e-08 4.96243605e-01]


In [52]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
print(new_y_pred)
cm = confusion_matrix(y_test, new_y_pred)
#Accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)

[0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 

In [53]:
cm

array([[16969,  3336],
       [ 1548, 20117]])

In [54]:
accuracy

0.8836311651179414

In [27]:
# need to have alex's code to merge track acoustics into each track's vector
# build a model for each song i (only look at 1st 10, train on 1st 5 songs + song i)
    # dataset for each model for x_train, y_train takes 1-5 + song i from session
    # split this data
    # build model
    # add prob from previous model